config/routes.rb
ToDoShredder::Application.routes.draw do
  
  resources :tasks do
    member do
      get :active
    end
  end

  root :to => 'sessions#new'
  match "/home", to: 'static_pages#home'
  match "/about", to: 'static_pages#about'

  get "static_pages/about"

  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match "/tasks",   to: 'task#index'

  resources :users

  resources :tests

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  attr_accessible :name, :notes, :status
  
  before_create :prepersist
  
  protected
    def prepersist
      self.status = true
    end
    
  def self.from_users_followed_by(user)
    followed_user_ids = user.followed_user_ids
    where("user_id IN (:followed_user_ids) OR user_id = :user_id",
          followed_user_ids: followed_user_ids, user_id: user)
  end   
  
  def self.findActiveTasksForUser(user)
    where("status = :status AND user_id = :user_id", status: true ,user_id: user)
  end 
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  
  # GET /tasks
  # GET /tasks.json
  def index
    #@tasks = Task.all
    @user = current_user
    @tasks = @user.tasks
    @displayShredder = true
    
    @hours = (Time.now - @user.loginTime)
    #if @hours > 2

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  # GET /tasks/1.xml
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
      format.xml { render xml: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  # GET /tasks/new.xml
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
      format.xml  { render xml: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  # POST /tasks.xml
  def create
    @task = current_user.tasks.build(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
        format.xml { render xml: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
        format.xml  { render xml:  @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  # PUT /tasks/1.xml
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
        format.xml  { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
        format.xml  { render xml: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  # DELETE /tasks/1.xml
  def destroy
    @deletedId = params[:id]
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.js   { }
      format.json { head :no_content }
      format.xml  { head :no_content }
    end
  end
  
  # GET /tasks/1/active
  def active
    #find all by status and from this user
    @tasks = Task.findActiveTasksForUser(current_user)
    
    #render '_active'    
    respond_to do |format|
      format.html { render '_active'    }
      format.js
    end
  end
  
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_active.html.erb
<table>
	<% @tasks.each do |task| %>
		  <tr>
		    <td><%= task.name %></td>
		    <td><%= task.notes %></td>
		    <td><%= task.user.loginTime %></td>
		    <td>
		    	<div class="btn-toolbar">
	  				<div class="btn-group">
			    	<%= link_to edit_task_path(task) do %>
						<span class="btn btn-default glyphicon glyphicon-edit tooltips" data-container="body" data-placement="bottom" data-title="Edit Task" > </span>
					<% end %>
					<%= link_to task, method: :delete, data: { confirm: 'Are you sure?' } do %>
						<span class="btn btn-default glyphicon glyphicon-remove-sign tooltips" data-container="body" data-placement="bottom" data-title="Delete Task" > </span>
					<% end %>
					<%= link_to task do %>
						<bspan class="btn btn-default glyphicon glyphicon-search tooltips" data-container="body" data-placement="bottom" data-title="View Task" /></span>
					<% end %>
					</div>
				</div>
		   </td>
		  </tr>
		<% end %>
</table>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<%= f.input :name %>
  <div class="field">
  	<%= f.input :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/active.js.erb
$(document).ready(function() {
	$("#modal-content").html("<table class='table table-hover'> <tr> <th>Task Name</th> <th>Description</th></tr>"+
		"<% @tasks.each do |task| %> <tr><td>  <%= task.name %> </td> <td>  <%= task.notes %> </td> </tr><% end %></table>");
});

app/views/tasks/destroy.js.erb
$("#task_row_<%= @deletedId %>").hide();

app/views/tasks/edit.html.erb
<h1><span class="glyphicon glyphicon-edit"></span> Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="container">
	<h1><span class="glyphicon glyphicon-list-alt"></span> Pending Tasks</h1>
	
	<div class="table-responsive"> 
		<table class="table">
		  <tr>
		    <th>Name</th>
		    <th>Notes</th>
		    <th>Alive since</th>
		    <th>Action</th>
		  </tr>
		
		<% if @hours < 2 %>
			<script type="text/javascript">$(document).ready(function() { showModal(); });</script>
		<% end %>
		
		<% @tasks.each do |task| %>
		  <tr id="task_row_<%= task.id %>">
		    <td><%= task.name %></td>
		    <td><%= task.notes %></td>
		    <td><%= task.updated_at %></td>
		    <td>
		    	<div class="btn-toolbar">
	  				<div class="btn-group">
			    	<%= link_to edit_task_path(task) do %>
						<span class="btn btn-default glyphicon glyphicon-edit tooltips" data-container="body" data-placement="bottom" data-title="Edit Task" > </span>
					<% end %>
					<%= link_to task, method: :delete,  data: { confirm: 'Are you sure?' }, :remote=>true do %>
						<span class="btn btn-default glyphicon glyphicon-remove-sign tooltips" data-container="body" data-placement="bottom" data-title="Delete Task" > </span>
					<% end %>
					<%= link_to task do %>
						<bspan class="btn btn-default glyphicon glyphicon-search tooltips" data-container="body" data-placement="bottom" data-title="View Task" /></span>
					<% end %>
					</div>
				</div>
		   </td>
		  </tr>
		<% end %>
		</table>
	</div>
	
	<br />
	
	<div class="row">
	  <div class="col-md-9">&nbsp;</div>
	  <div class="col-md-3">
	  	<%= link_to new_task_path do %>
			<button class="btn btn-default btn-lg"><span class="glyphicon glyphicon-plus-sign"></span>   Write another to-do</button>
		<% end %>
		</div>
	</div>
</div>

	<%= link_to 'Destroy', active_task_path(@tasks[0]), :method => :get, :remote=>true, :class=>'hidden', :id=>'shredder', :dataType => 'script' %>
	

 <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Burn pending tasks</h4>
        </div>
        <div class="modal-body" id="modal-content">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<div class="container"> 

<h1><span class="glyphicon glyphicon-search"></span> Task Information</h1>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Notes:</b>
  <%= @task.notes %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

</div>