config/routes.rb
ToDoShredder::Application.routes.draw do
  
  resources :tasks do
    member do
      get :active
    end
  end

  root :to => 'sessions#new'
  match "/home", to: 'static_pages#home'
  match "/about", to: 'static_pages#about'

  get "static_pages/about"

  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match "/tasks",   to: 'task#index'

  resources :users

  resources :tests

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoShredder</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	 <% if signed_in? %>
		<div class="navbar navbar-fixed-top navbar-inverse" role="navigation" >
	      <div class="container">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          <a class="navbar-brand" href="#">
	          	<span class="glyphicon glyphicon-fire"></span>
	          	 To-Do Shredder</a>
	        </div>
	        <div class="collapse navbar-collapse">
	            
	            
	          <ul class="nav navbar-nav navbar-right">  
	            <li class="dropdown">
			    	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Actions <b class="caret"></b></a>
			        <ul class="dropdown-menu">
			        	<li>
			        		<%= link_to tasks_path do %>
								<span class="glyphicon glyphicon-list-alt"></span> To-Do's
							<% end %>
						</li>
			        	<li>
			        		<%= link_to signout_path, method: "delete" do %>
								<span class="glyphicon glyphicon-trash"></span> Shredder
							<% end %>
						</li>
	            		<li>
	            			<%= link_to signout_path, method: "delete" do %>
								<span class="glyphicon glyphicon-off"></span> Sign Out
							<% end %>
	            		</li>
			        </ul>
			     </li>
	          </ul>
	        </div><!-- /.nav-collapse -->
	      </div><!-- /.container -->
	    </div><!-- /.navbar -->
	<% end %>
	
	<div style="margin-top:70px;">
	
		<div class="container">
			<% if flash[:alert] %>
			    <p class="flash-error"><%= flash[:alert] %></p>
			  <% end %>
			  <% if flash[:notice] %>
			    <p id="notice"><%= flash[:notice] %></p>
			  <% end %>
			   <% if flash[:error] %>
			    <p id="notice"><%= flash[:error] %></p>
			  <% end %>
		</div>	
		<div class="container">
			<%= yield %>
		</div>
	</div>
	
</body>
</html>